config/routes.rb
Rails.application.routes.draw do

  root 'players#index'

  get '/all_matches' => 'matches#all_matches'
  get '/match/:id/close' => 'matches#close'
  get '/match/:id/reopen' => 'matches#reopen'
  patch '/match/:id/setscores' => 'matches#set_scores', as: :match

  resources :players, except: [:index]
  resources :games do
    resources :badges
    resources :matches
  end
  resources :tags, only: [:index]
end

app/models/badge.rb
class Badge < ActiveRecord::Base
  belongs_to :game
  has_and_belongs_to_many :players
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :badges
  has_many :matches
  has_many :scores, through: :matches
  has_many :players, through: :scores

  def average_duration
    return 0 if self.matches.count == 0
    total_duration = 0
    self.matches.each { |match| total_duration += match.duration }
    beautify_time(total_duration / (self.matches.count))
  end

  def beautify_time total_minutes
    hours = total_minutes / 60
    minutes = total_minutes % 60
    beautified_string = "#{hours} hores"
    beautified_string += "i #{minutes} minuts" unless minutes == 0
    beautified_string
  end

  def most_played_by
    [Player.first]
  end

  def average_number_of_players
    (self.matches.reduce(0) { |all_players, match| all_players + match.players.count }) / self.matches.count.to_f
  end
end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :game
  has_many :scores, dependent: :destroy
  has_many :players, through: :scores
  scope :opened, -> { where(open_status: true).ordered }
  scope :closed, -> { where(open_status: false).ordered }
  scope :ordered, -> { order(open_status: :desc).order(created_at: :desc) }
  accepts_nested_attributes_for :scores
  validates :duration, presence: true, numericality: {greater_than: 0}, on: :update, if: "closed?"

  def beautified_created_at
    created_at.strftime("%-d.%-m.%Y a les %l:%Mh %P")
  end

  def reset_scores_and_duration
    duration = 0
    scores.map { |score| score.points = 0;score.save }
  end

  def closed?
    !open_status
  end
end

app/models/player.rb
class Player < ActiveRecord::Base
  has_many :scores, dependent: :destroy
  has_many :matches, through: :scores
  has_many :games, through: :matches
  has_and_belongs_to_many :badges

  def total_points
    total = 0
    self.scores.each do |score|
      total += score.points
    end
    total
  end

  def total_score_for game
    total_score = 0
    scores.select {|score| score.game.id == game.id }.each { |score| total_score += score.points}
    total_score
  end
end

app/models/score.rb
class Score < ActiveRecord::Base
  belongs_to :match
  belongs_to :player
  has_one :game, through: :match
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController

  before_filter :find_game

  def new
    @badge = Badge.new
  end

  def create
    Badge.save badge_params.merge(game_id: @game.id)
  rescue
    render :new
  end

  def assign_badge
    player = Player.find params[:id]
  end

  private
  def badge_params
    params.require(:badge).permit(:title, :points, :game_id)
  end

  def find_game
    @game = Game.find params[:game_id]
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.order(:id)
  end

  def show
    @game = Game.find params[:id]
    @players = @game.players.sort_by { |player| player.total_score_for @game }.uniq.reverse
  end

  def new
    @game = Game.new
  end

  def edit
    @game = Game.find params[:id]
  end

  def update
    @game = Game.find params[:id]
    @game.update game_params
    redirect_to games_path
  rescue
    render :edit
  end

  def create
    @game = Game.create game_params
    flash[:notice] = "Joc afegit!"
    redirect_to games_path
  rescue
    render :new
  end

  def game_params
    params.require(:game).permit(:title, :game_type)
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

  before_filter :find_game, only: [:new, :index, :create]

  def all_matches
    @matches = (params[:tab] == "closed") ? Match.closed : Match.opened
  end

  def index
    @matches = Match.where(game_id: @game.id).ordered
  end

  def new
    @match = Match.new
    @players = Player.all
  end

  def create
    match = Match.new game_id: @game.id
    params[:match][:players].each do |hidden_field_hash|
      match.scores << Score.create(player_id: hidden_field_hash.last["player_id"])
    end
    match.save
    redirect_to game_matches_path(match.game)
  end

  def destroy
    match = Match.find params[:id]
    match.destroy
    redirect_to game_matches_path(match.game)
  end

  def close
    @match = Match.find params[:id]
  end

  def set_scores
    match = Match.find params[:id]
    match.update match_params.merge(open_status: false)
    redirect_to root_path
  end

  def reopen
    match = Match.find params[:id]
    match.update(open_status: true, duration: 0)
    match.reset_scores_and_duration
    redirect_to game_matches_path(match.game_id)
  end

  def match_params
    params.require(:match).permit(:duration, scores_attributes: [:points, :id])
  end

  def find_game
    @game = Game.find params[:game_id]
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def new
    @player = Player.new
  end

  def create
    Player.create player_params
    redirect_to root_path
  end

  def show
    @player = Player.find(params[:id])
  end

  def index
    unsorted_players = Player.all
    @players = unsorted_players.sort_by { |player| player.total_points }.reverse
  end

  def destroy
    player = Player.find params[:id]
    player.destroy
    redirect_to root_path
  end

  def player_params
    params.require(:player).permit(:name)
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def make_active_if_it_matches given_url
    "active" if given_url == request.original_fullpath
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
  def display_opened_or_closed
    (params[:tab] == "closed") ? "tancades" : "en disputa"
  end

  def display_duration_or_opened match
    (match.duration == 0) ? "en disputa" : "#{match.duration} min"
  end

  def display_players_for match
    all_players = ""
    match.players.each do |player|
      all_players += "#{ link_to player.name, player_path(player.id) } "
    end
    all_players.html_safe
  end

  def link_to_reopen_or_close match
    match.open_status ? link_to("Tanca-la", "/match/#{match.id}/close") : link_to("Reobre-la", "/match/#{match.id}/reopen")
  end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/games/_form.html.erb
<%= form_for @game do |f| %>
  <%= f.label :title, "Títol" %>
  <%= f.text_field :title, class: "form-control", autofocus: true %><br />
  <%= f.label :game_type, "Tipus de joc" %>
  <%= f.text_field :game_type, class: "form-control" %><br />
  <%= f.submit "Guardar", :disable_with => 'Guardant...', class: "btn btn-primary" %>
<% end %>

app/views/games/_matches.html.erb
<table class="table table-responsive table-striped table-hover">
  <tr>
    <th>Data</th>
    <th>Durada</th>
    <th>Jugadors</th>
    <th>Accions</th>
  </tr>
  <tbody>
    <% @game.matches.order(:created_at).each do |match| %>
      <tr>
        <td><%= match.beautified_created_at %></td>
        <td><%= display_duration_or_opened match %></td>
        <td><%= display_players_for match %></td>
        <td><%= link_to_reopen_or_close match %> | 
        <%= link_to "Elimina-la", game_match_path(match.game_id, match.id), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/games/edit.html.erb
<h1>Edita la informació del <%= @game.title %></h1>
<section class="lil-form-container">
  <%= render 'form' %>
</section>

app/views/games/index.html.erb
<h1>Jocs!</h1>

<table class="table table-responsive table-striped table-hover">
  <thead>
    <tr>
      <th>T&iacute;tol</th>
      <th>Tipus</th>
      <th>N&uacute;mero de Badges</th>
      <th>N&uacute;mero de partides jugades</th>
      <th>Mitjana de temps per partida</th>
      <th>Accions</th>
    </tr>
  </thead>
  <% @games.each do |game| %>
    <tr>
      <td><%= link_to game.title, game_path(game) %> <%= hidden_field_tag :game_id, game.id %></td>
      <td><%= game.game_type %></td>
      <td><%= game.badges.count %></td>
      <td><%= link_to game.matches.count, game_matches_path(game) %></td>
      <td><%= game.average_duration %></td>
      <td><%= link_to "Editar", edit_game_path(game) %> | <%= link_to "Crear nova partida", new_game_match_path(game) %></td>
    </tr>
    <% end %>
</table>

app/views/games/new.html.erb
<h1>Afegeix un joc nou</h1>
<section class="lil-form-container">
  <%= form_for @game do |f| %>
    <%= f.label :title, "Títol" %>
    <%= f.text_field :title, class: "form-control" %><br />
    <%= f.label :game_type, "Tipus de joc" %>
    <%= f.text_field :game_type, class: "form-control" %><br />
    <%= f.submit "Afegir", :disable_with => 'Afegint...', class: "btn btn-primary" %>
  <% end %>
</section>

app/views/games/show.html.erb
<h1><%= @game.title %></h1>
<section id="ranking">
  <table class="table table-responsive table-striped table-hover">
    <thead>
      <th>#</th>
      <th>Jugador</th>
      <th>Punts</th>
    </thead>
    <% @players.each.with_index do |player, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= player.name %></td>
        <td><%= player.total_score_for @game %></td>
      </tr>
    <% end %>
  </table>
</section>
<section id="info" class="panel panel-primary">
  <ul>
    <li>Propietari: <%= @game.owner %></li>
    <li>Localització: <%= @game.location %></li>
    <li>Número de badges: <%= @game.badges.count %></li>
    <li>Número de partides jugades: <%= @game.matches.count %></li>
    <li>Mitjana de jugadors per partida: <%= @game.average_number_of_players %></li>
    <li>Durada mitjana: <%= @game.average_duration %></li>
    <li>Jugadors que més hi han jugat:
      <ul>
        <% @game.most_played_by.each do |player| %>
          <li><%= player.name %></li>
        <% end %>
      </ul>
    </li>
    <li>Expansions:</li>
  </ul>
</section>
<section id="badges" class="panel panel-primary">
  <div id="left-arrow" class="panel arrow"></div>
  <div id="right-arrow" class="panel arrow"></div>
    <ul id="badge-list">
      <li class="<%=  %>"><img src="https://trello-attachments.s3.amazonaws.com/5452be48608d7c7697fd8637/200x200/104e1591f653987d16789df95862738f/Sex_change.png"></li>
      <li class="<%=  %>"><img src="https://trello-attachments.s3.amazonaws.com/5452be48608d7c7697fd8637/200x200/104e1591f653987d16789df95862738f/Sex_change.png"></li>
      <li class="<%=  %>"><img src="https://trello-attachments.s3.amazonaws.com/5452be48608d7c7697fd8637/200x200/104e1591f653987d16789df95862738f/Sex_change.png"></li>
      <li class="<%=  %>"><img src="https://trello-attachments.s3.amazonaws.com/5452be48608d7c7697fd8637/200x200/104e1591f653987d16789df95862738f/Sex_change.png"></li>
      <li class="<%=  %>"><img src="https://trello-attachments.s3.amazonaws.com/5452be48608d7c7697fd8637/200x200/104e1591f653987d16789df95862738f/Sex_change.png"></li>
    </ul>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ALSFr</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <ul class="nav nav-pills nav-stacked">
    <li class="<%= make_active_if_it_matches "/" %>"><a href="/">Marcador</a></li>
    <li class="<%= make_active_if_it_matches "/games" %>"><a href="/games">Llistat de jocs</a></li>
    <li class="<%= make_active_if_it_matches "/all_matches" %> <%= make_active_if_it_matches "/all_matches?tab=closed" %>"><a href="/all_matches">Partides</a></li>
    <li class="<%= make_active_if_it_matches "/tags" %>"><a href="/tags">N&uacute;vol de tags</a></li>
    <li class="<%= make_active_if_it_matches "/players/new" %>"><a href="/players/new">Afegir jugador</a></li>
    <li class="<%= make_active_if_it_matches "/games/new" %>"><a href="/games/new">Afegir joc</a></li>
  </ul>
  <article class="main">
    <%= yield %>
  </article>
</body>
</html>

app/views/matches/all_matches.html.erb
<h1>Partides <%= display_opened_or_closed %></h1>
<a href="/all_matches"><button class="btn btn-primary">En disputa</button></a> | <a href="/all_matches?tab=closed"><button class="btn btn-primary">Tancades</button></a> <br/>
<table class="table table-responsive table-striped table-hover">
  <thead>
    <tr>
      <th>Joc</th>
      <th>Data</th>
      <th>Durada</th>
      <th>Jugadors</th>
      <th>Accions</th>
    </tr>
  </thead>
  <tbody class="">
    <% @matches.each do |match| %>
      <tr>
        <td><%= link_to match.game.title, game_path(match.game) %></td>
        <td><%= match.beautified_created_at %></td>
        <td><%= display_duration_or_opened match %></td>
        <td><%= display_players_for match %></td>
        <td><%= link_to_reopen_or_close match %> | 
        <%= link_to "Elimina-la", game_match_path(match.game_id, match.id), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/matches/close.html.erb
<h1>Tanca la partida de <%= @match.game.title %> del <%= @match.beautified_created_at %></h1>
<h3>Punts</h3>
<section class="lil-form-container smallest">
  <%= form_for [@match] do |f| %>
    <% @match.scores.each do |this_score| %>
      <%= f.fields_for :scores, this_score do |sf| %>
        <%= sf.label this_score.player.name %>
        <%= sf.text_field :points, class: "form-control" %>
      <% end %>
    <% end %>
    <%= f.label :duration, "Durada (en minuts)" %> <br />
    <%= f.text_field :duration, class: "form-control" %>
    <%= f.submit "Enviar puntuació", :disable_with => 'Enviant...', class: "btn btn-primary" %>
  <% end %>
</section>

app/views/matches/index.html.erb
<h1>Partides del <%= @game.title %></h1>
<table class="table table-responsive table-striped table-hover">
  <thead>
    <tr>
      <th>Data</th>
      <th>Durada</th>
      <th>Jugadors</th>
      <th>Accions</th>
    </tr>
  </thead>
  <tbody>
    <% @matches.each do |match| %>
      <tr>
        <td><%= match.beautified_created_at %></td>
        <td><%= display_duration_or_opened match %></td>
        <td><%= display_players_for match %></td>
        <td><%= link_to_reopen_or_close match %> | 
        <%= link_to "Elimina-la", game_match_path(match.game_id, match.id), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/matches/new.html.erb
<h1>Crea una nova partida de <%= @game.title %></h1>
<section class="lil-form-container">
  <%= form_for [@game, @match], html: { class: "clearfix" } do |f| %>
    <%= f.label :players, "Jugadors" %> 
    <br />
    <div id="from" ondrop="dropIt(event);" ondragover="event.preventDefault();">
      <% @players.each do |player| %>
        <span draggable="true" ondragstart="dragIt(event);" class="player" id="<%= player.id%>"><%= player.name%></span>
      <% end %>
    </div>
    <div id="to" ondrop="dropIt(event);" ondragover="event.preventDefault();">
    </div>
    <%= f.submit "Començar la partida", id: "newMatchSubmit", :disable_with => 'Afegint jugadors...', class: "btn btn-primary" %>
  <% end %>
</section>

app/views/players/index.html.erb
<h1>RellotgesDeLaParetDelGranSal&oacute;DeLaSeuNoEstivalDeLALSFr</h1>

<table class="table table-responsive table-striped table-hover">
  <thead>
    <tr>
      <th>Posici&oacute;</th>
      <th>Nom</th>
      <th>N&uacute;mero de Badges</th>
      <th>Punts totals</th>
      <th>Accions</th>
    </tr>
  </thead>
  <tbody class="">
    <% @players.each.with_index do |player, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= player.name %></td>
        <td><%= player.badges.count %></td>
        <td><%= player.total_points %></td>
        <td><%= link_to "Editar", edit_player_path(player) %> | <%= link_to "Eliminar", player_path(player), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/players/new.html.erb
<h1>Afegeix un nou jugador</h1>
<section class="lil-form-container">
  <%= form_for @player do |f| %>
    <%= f.label :name, "Nom" %>
    <%= f.text_field :name, class: "form-control", autofocus: true %><br />
    <%= f.submit "Afegir", :disable_with => 'Afegint...', class: "btn btn-primary" %>
  <% end %>
</section>

app/views/tags/index.html.erb
<h1>Encara no...</h1>